version: "3.2"
services:
  mariadb:
    image: mariadb:10.5.9
    container_name: g2_mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ~/docker/volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "g2-prototype-pw"

  # For use of confluentinc/... images, only version 6.0.x can be used.
  # Only this version is compatible to kafka-clients 2.6.0, which is used by this spring version.
  # see https://docs.confluent.io/platform/current/installation/versions-interoperability.html for more informations.
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.2
    hostname: zookeeper
    container_name: g2_zookeeper
    restart: always
    ports:
      - "2181:2181"
#    volumes:
#      - ~/docker/volumes/zookeeper:/var/lib/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

#  kafka-0:
#    image: bitnami/kafka:2.8.0
#    container_name: g2_kafka-0
#    restart: always
#    ports:
#      - 29092:9092
##    volumes:
##      - ~/docker/volumes/kafka/kafka-0:/bitnami/kafka
#    environment:
#      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
#      ALLOW_PLAINTEXT_LISTENER: "yes"
#      KAFKA_LISTENERS: >-
#        INTERNAL://:9092,EXTERNAL://:29092
#      KAFKA_ADVERTISED_LISTENERS: >-
#        INTERNAL://kafka-0:9092,EXTERNAL://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
#        INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
#    depends_on:
#      - zookeeper

  kafka-0:
    image: confluentinc/cp-kafka:6.0.2
    hostname: kafka-0
    container_name: g2_kafka-0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
#    volumes:
#      - ~/docker/volumes/kafka/kafka-0:/var/lib/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka-0:9092,EXTERNAL://localhost:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-0:9092,EXTERNAL://localhost:29092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-1:
    image: confluentinc/cp-kafka:6.0.2
    hostname: kafka-1
    container_name: g2_kafka-1
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "29093:29092"
#    volumes:
#      - ~/docker/volumes/kafka/kafka-1:/var/lib/kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://localhost:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://localhost:29093
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-2:
    image: confluentinc/cp-kafka:6.0.2
    hostname: kafka-2
    container_name: g2_kafka-2
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "29094:29092"
#    volumes:
#      - ~/docker/volumes/kafka/kafka-2:/var/lib/kafka
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka-2:9092,EXTERNAL://localhost:29094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,EXTERNAL://localhost:29094
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  schema-registry:
    image: confluentinc/cp-schema-registry:6.0.2
    hostname: schema-registry
    container_name: g2_schema-registry
    depends_on:
      - zookeeper
      - kafka-0
      - kafka-1
      - kafka-2
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: >-
        kafka-0:9092,kafka-1:9092,kafka-2:9092

  kowl:
    image: quay.io/cloudhut/kowl:v1.3.1
    container_name: g2_kowl
    restart: always
    ports:
      - 9000:8080
    environment:
      KAFKA_BROKERS: >-
        kafka-0:9092,kafka-1:9092,kafka-2:9092
      KAFKA_SCHEMAREGISTRY_URLS: >-
        http://schema-registry:8081
    depends_on:
      - zookeeper
      - kafka-0
      - kafka-1
      - kafka-2
      - schema-registry
